name: cli_async_redux
description: A lightweight Redux implementation for CLI applications with async action support.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.11.4

dependencies:
  collection: ^1.19.1
  meta: ^1.18.2

dev_dependencies:
  pro_lints: ^5.1.0
