name: lsp_protocol
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
  
dependencies:
  async: ^2.13.0
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_rpc_2: ^4.0.0
  stream_channel: ^2.1.4
  

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  pro_lints: ^4.0.0
  test: ^1.26.3

