name: pro_lsp
description: Unified LSP 3.17 Dart bindings and server API implementation.
version: 0.1.0

environment:
  sdk: "^3.10.0"

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  json_rpc_2: ^4.1.0
  stream_channel: ^2.1.4

dev_dependencies:
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  pro_lints: ^6.1.0
  test: ^1.31.1
