name: generate
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  code_builder: ^4.10.1
  equatable: ^2.0.7
  http: ^1.4.0
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.3
  json_serializable: ^6.9.5
  pro_lints: ^4.0.0
  test: ^1.26.2
