name: lsp_specification
description: Generated LSP 3.17 Dart bindings.
version: 0.1.0

environment:
  sdk: "^3.0.0"

dependencies:
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.13.1
  freezed: ^3.2.5
