name: generator
description: LSP Protocol Generator
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.3

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  code_builder: ^4.11.1
  collection: ^1.19.1
  dart_style: ^3.1.7
  equatable: ^2.0.8
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  json_annotation: ^4.11.0
  path: ^1.9.1

dev_dependencies:
  build_runner: ^2.13.1
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  pro_lints: ^5.1.0
  test: ^1.31.0
