name: lsp_server
description: Typed LSP server implementation over json_rpc_2 with namespace-grouped handler API.
version: 0.1.0

publish_to: none

environment:
  sdk: "^3.11.4"

dependencies:
  json_rpc_2: ^4.1.0
  stream_channel: ^2.1.4
  lsp_specification:
    path: ../lsp_specification

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
